# Generated by Django 2.2.1 on 2019-05-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=512)),
                ('last_name', models.CharField(blank=True, max_length=512)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
